### ISSUE TITLE
Dispersy.stop is causing random exceptions

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#169]
We're  seeing random errors while shutting down Dispersy on the das. This is currently causing all our builds to be marked as failed.

Examples:

```
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: INFO    1385727328.35        dispersy:1064  update connection type unknown -> public
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: Exception in thread Dispersy (most likely raised during interpreter shutdown):
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: Traceback (most recent call last):
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT:   File "/home/emilon/venv/inst/lib/python2.7/threading.py", line 808, in __bootstrap_inner
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT:   File "/home/emilon/venv/inst/lib/python2.7/threading.py", line 761, in run
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT:   File "/var/scratch/emilon/jenkins/workspace/Experiment_Demers_devel/tribler/Tribler/dispersy/callback.py", line 693, in loop
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'


2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: INFO    1385727328.38        dispersy:1064  update connection type unknown -> public
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: Exception in thread StandaloneEndpoint (most likely raised during interpreter shutdown):
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: Traceback (most recent call last):
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT:   File "/home/emilon/venv/inst/lib/python2.7/threading.py", line 808, in __bootstrap_inner
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT:   File "/home/emilon/venv/inst/lib/python2.7/threading.py", line 761, in run
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT:   File "/var/scratch/emilon/jenkins/workspace/Experiment_Demers_devel/tribler/Tribler/dispersy/endpoint.py", line 304, in _loop
2013-11-29 13:25:08+0100 [-] CMD "post_process_dispersy_experiment.sh" OUT: <type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by NielsZeilemaker** [comment]
@boudewijn-tribler any update on this? These error make hunting for exceptions virtually impossible.

**Comment by boudewijn-tribler** [comment]
Looking into it now.

**Comment by NielsZeilemaker** [comment]
@LipuFei these are caused by Dispersy having global loggers, could you convert these into separate loggers per class like we have in Tribler?

**Comment by NielsZeilemaker** [comment]
Should be fixed
