### ISSUE TITLE
Failed assert in message.py

### ISSUE THREAD

**Issue by whirm** [Tribler/dispersy#362]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 1192, in take_step
    self.create_introduction_request(candidate, self.dispersy_enable_bloom_filter_sync)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 2628, in create_introduction_request
    self.flush_batch_cache()
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 2100, in flush_batch_cache
    self._process_message_batch(meta)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 2036, in _process_message_batch
    return self._on_batch_cache(meta, batch)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 2065, in _on_batch_cache
    messages.append(conversion.decode_message(candidate, packet))
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/util.py", line 183, in wrapper
    return_value = func(*args, **kargs)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/conversion.py", line 1277, in decode_message
    placeholder.offset, placeholder.payload = decode_functions.payload(placeholder, placeholder.offset, placeholder.data[:placeholder.first_signature_offset])
  File "/var/data/feina/code/delft/tribler/Tribler/community/channel/conversion.py", line 359, in _decode_modification
    raise DelayPacketByMissingMessage(self._community, member, modification_on_global_time)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/message.py", line 92, in __init__
    assert isinstance(member, Member)
exceptions.AssertionError: 
```

**Comment by NielsZeilemaker** [comment]
Added a type print in pull request #410, lets see if it happens again
