### ISSUE TITLE
assert in estimate_lan_and_wan_addresses

### ISSUE THREAD

**Issue by whirm** [Tribler/dispersy#364]
Found this on one of the tracker's logs.

```
2014-08-18 20:38:00+0000 [StandaloneEndpoint (UDP)] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 147, in doRead
            self.protocol.datagramReceived(data, addr)
          File "/home/tracker/dispersy/endpoint.py", line 323, in datagramReceived
            self._dispersy.on_incoming_packets([(Candidate(address, is_tunnel), datagram)], timestamp=time())
          File "/home/tracker/dispersy/dispersy.py", line 1456, in on_incoming_packets
            community.on_incoming_packets(list(iterator), cache, timestamp)
          File "/home/tracker/dispersy/community.py", line 1991, in on_incoming_packets
            self._on_batch_cache(meta, batch)
          File "/home/tracker/dispersy/community.py", line 2060, in _on_batch_cache
            self.on_messages(messages)
          File "/home/tracker/dispersy/community.py", line 2172, in on_messages
            if self._dispersy.store_update_forward(possibly_messages, True, True, False):
          File "/home/tracker/dispersy/dispersy.py", line 1694, in store_update_forward
            if self._update(possibly_messages) == False:
          File "/home/tracker/dispersy/util.py", line 183, in wrapper
            return_value = func(*args, **kargs)
          File "/home/tracker/dispersy/dispersy.py", line 1719, in _update
            messages[0].handle_callback(messages)
          File "/home/tracker/dispersy/tracker/community.py", line 161, in on_introduction_request
            return super(TrackerCommunity, self).on_introduction_request(messages)
          File "/home/tracker/dispersy/community.py", line 2425, in on_introduction_request
            candidate = self.create_or_update_walkcandidate(message.candidate.sock_addr, message.payload.source_lan_address, message.payload.source_wan_address, message.candidate.tunnel, message.payload.connection_type, message.candidate)
          File "/home/tracker/dispersy/community.py", line 1464, in create_or_update_walkcandidate
            lan_address, wan_address = self._dispersy.estimate_lan_and_wan_addresses(sock_addr, lan_address, wan_address)
          File "/home/tracker/dispersy/dispersy.py", line 1616, in estimate_lan_and_wan_addresses
            assert self.is_valid_address(sock_addr), sock_addr
        exceptions.AssertionError: ('XXXXXXXXXX', 0)
```

Where XXXXXXXXXX is a valid IP.

**Comment by NielsZeilemaker** [comment]
This one and #401 is similar, somehow the sock_addr port is 0. Let's add an assert in the endpoint to see if it happens there.

**Comment by NielsZeilemaker** [comment]
This can't really happen anymore, as there is a check on the post of the sock_addr in on_incoming_packets and in the constructor of a candidate. I'll close both issues to see if it happens again.
