### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_puncture'

### ISSUE THREAD

**Issue by LipuFei** [Tribler/dispersy#383]
See https://github.com/Tribler/tribler/issues/985 also

```
Traceback (most recent call last):
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/community.py", line 2850, in on_puncture
    cache.on_puncture()
AttributeError: 'NoneType' object has no attribute 'on_puncture'
```

**Comment by NielsZeilemaker** [comment]
This can only happen if we receive two puncture requests for the same identifier in a single batch.
