### ISSUE TITLE
[tracker] assert isinstance(member, Member)

### ISSUE THREAD

**Issue by LipuFei** [Tribler/dispersy#399]
A backtrace in tracker log:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 147, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/home/tracker/dispersy/endpoint.py", line 323, in datagramReceived
    self._dispersy.on_incoming_packets([(Candidate(address, is_tunnel), datagram)], timestamp=time())
  File "/home/tracker/dispersy/dispersy.py", line 1456, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp)
  File "/home/tracker/dispersy/community.py", line 2009, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/tracker/dispersy/community.py", line 2078, in _on_batch_cache
    self.on_messages(messages)
  File "/home/tracker/dispersy/community.py", line 2190, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/tracker/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/tracker/dispersy/util.py", line 183, in wrapper
    return_value = func(*args, **kargs)
  File "/home/tracker/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/tracker/dispersy/discovery/community.py", line 601, in on_intro_request
    message.payload.introduce_me_to)
  File "/home/tracker/dispersy/discovery/community.py", line 614, in get_tb_or_candidate_mid
    return self.get_candidate_mid(mid)
  File "/home/tracker/dispersy/community.py", line 1516, in get_candidate_mid
    if candidate.is_associated(member):
  File "/home/tracker/dispersy/candidate.py", line 70, in is_associated
    assert isinstance(member, Member)
exceptions.AssertionError:

```

**Comment by NielsZeilemaker** [comment]
Fixed by #409
