### ISSUE TITLE
[tracker] exceptions.AssertionError: ('108.5.165.90', 0)

### ISSUE THREAD

**Issue by LipuFei** [Tribler/dispersy#401]
A backtrace in tracker log:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 147, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/home/tracker/dispersy/endpoint.py", line 323, in datagramReceived
    self._dispersy.on_incoming_packets([(Candidate(address, is_tunnel), datagram)], timestamp=time())
  File "/home/tracker/dispersy/dispersy.py", line 1456, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp)
  File "/home/tracker/dispersy/community.py", line 2009, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/tracker/dispersy/community.py", line 2078, in _on_batch_cache
    self.on_messages(messages)
  File "/home/tracker/dispersy/community.py", line 2190, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/tracker/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/tracker/dispersy/util.py", line 183, in wrapper
    return_value = func(*args, **kargs)
  File "/home/tracker/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/tracker/dispersy/discovery/community.py", line 478, in on_similarity_request
    message.payload.connection_type, message.candidate)
  File "/home/tracker/dispersy/community.py", line 1482, in create_or_update_walkcandidate
    lan_address, wan_address = self._dispersy.estimate_lan_and_wan_addresses(sock_addr, lan_address, wan_address)
  File "/home/tracker/dispersy/dispersy.py", line 1616, in estimate_lan_and_wan_addresses
    assert self.is_valid_address(sock_addr), sock_addr
exceptions.AssertionError: ('108.5.165.90', 0)
```

**Comment by LipuFei** [comment]
Got another one in tracker log:

```
Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 402, in startReactor
        self.config, oldstdout, oldstderr, self.profiler, reactor)
      File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 323, in runReactorWithLogging
        reactor.run()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1169, in run
        self.mainLoop()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
        self.runUntilCurrent()
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 773, in runUntilCurrent
        f(*a, **kw)
      File "/home/tracker/dispersy/endpoint.py", line 184, in dispersythread_data_came_in
        timestamp)
      File "/home/tracker/dispersy/dispersy.py", line 1457, in on_incoming_packets
        community.on_incoming_packets(list(iterator), cache, timestamp)
      File "/home/tracker/dispersy/community.py", line 2033, in on_incoming_packets
        self._on_batch_cache(meta, batch)
      File "/home/tracker/dispersy/community.py", line 2103, in _on_batch_cache
        self.on_messages(messages)
      File "/home/tracker/dispersy/community.py", line 2217, in on_messages
        if self._dispersy.store_update_forward(possibly_messages, True, True, False):
      File "/home/tracker/dispersy/dispersy.py", line 1693, in store_update_forward
        if self._update(possibly_messages) == False:
      File "/home/tracker/dispersy/util.py", line 151, in wrapper
        return_value = func(*args, **kargs)
      File "/home/tracker/dispersy/dispersy.py", line 1718, in _update
        messages[0].handle_callback(messages)
      File "/home/tracker/dispersy/tracker/community.py", line 161, in on_introduction_request
        return super(TrackerCommunity, self).on_introduction_request(messages)
      File "/home/tracker/dispersy/community.py", line 2477, in on_introduction_request
        candidate = self.create_or_update_walkcandidate(message.candidate.sock_addr, message.payload.source_lan_address, message.payload.source_wan_address, message.candidate.tunnel, message.payload.connection_type, message.candidate)
      File "/home/tracker/dispersy/community.py", line 1511, in create_or_update_walkcandidate
        wcandidate.update(tunnel, lan_address, wan_address, connection_type)
      File "/home/tracker/dispersy/candidate.py", line 296, in update
        assert lan_address == ("0.0.0.0", 0) or is_valid_address(lan_address), lan_address
    exceptions.AssertionError: ('0.0.0.0', 51691)
```
