### ISSUE TITLE
ActualTasteBuddy' object has no attribute 'timestamp

### ISSUE THREAD

**Issue by rjruigrok** [Tribler/dispersy#431]
```
AttributeError: 'ActualTasteBuddy' object has no attribute 'timestamp'
ERROR   1434629686.80        dispersy:1724  exception during handle_callback for ping
Traceback (most recent call last):
  File "/home/tribler/git/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/tribler/git/tribler/Tribler/dispersy/discovery/community.py", line 685, in on_ping
    self.reset_taste_buddy(message.candidate)
  File "/home/tribler/git/tribler/Tribler/dispersy/discovery/community.py", line 336, in reset_taste_buddy
    for tb in self.yield_taste_buddies():
  File "/home/tribler/git/tribler/Tribler/dispersy/discovery/community.py", line 310, in yield_taste_buddies
    if self.taste_buddies[i].time_remaining() == 0:
  File "/home/tribler/git/tribler/Tribler/dispersy/discovery/community.py", line 89, in time_remaining
    diff = self.timestamp - too_old
AttributeError: 'ActualTasteBuddy' object has no attribute 'timestamp'
```

**Comment by NielsZeilemaker** [comment]
The crazy thing is, it does have a timestamp attribute:
https://github.com/Tribler/dispersy/blob/devel/discovery/community.py#L80

**Comment by rjruigrok** [comment]
Other strange error also occuring in this part. 
Don't know how if there is any correlation with this, but I'm running the latest tribler, with a test download over hidden services in the session. 

``````
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rob/git/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/rob/git/tribler/Tribler/dispersy/endpoint.py", line 247, in dispersythread_data_came_in
    u"standalone_ep")
  File "/home/rob/git/tribler/Tribler/dispersy/dispersy.py", line 1458, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/home/rob/git/tribler/Tribler/dispersy/community.py", line 2023, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/rob/git/tribler/Tribler/dispersy/community.py", line 2093, in _on_batch_cache
    self.on_messages(messages)
  File "/home/rob/git/tribler/Tribler/dispersy/community.py", line 2207, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/rob/git/tribler/Tribler/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/rob/git/tribler/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/home/rob/git/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/rob/git/tribler/Tribler/dispersy/discovery/community.py", line 608, in on_similarity_response
    w_candidate)])
  File "/home/rob/git/tribler/Tribler/dispersy/discovery/community.py", line 87, in __init__
    assert candidate.get_member()
exceptions.AssertionError: ```
``````

**Comment by NielsZeilemaker** [comment]
This second one is fixed in https://github.com/Tribler/dispersy/pull/436, as for the first one that unreproducable.
