### ISSUE TITLE
Dispersy.stop() problems

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#6]
We are experiencing some problems with the Dispersy.stop() method in regard to the timeout property. If the callback is not able to stop during this time it will return before running all expired tasks. Which by itself is I guess expected.

However, if one of those not yet run expired tasks is a dispersythread_data_came_in task, things will break. The Dispersy.stop() method now has cleaned/removed all singletons, and hence we get stracktraces like:

``` python
E         dispersy/callback:679  _loop                     | 
Traceback (most recent call last):
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/callback.py", line 677, in _loop
    result = call[0](*call[1], **call[2])
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/endpoint.py", line 136, in dispersythread_data_came_in
    timestamp)
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/dispersy.py", line 1786, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/dispersy.py", line 1858, in _on_batch_cache
    messages = list(self._convert_batch_into_messages(batch))
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/dispersy.py", line 2061, in _convert_batch_into_messages
    yield conversion.decode_message(candidate, packet)
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/conversion.py", line 1408, in decode_message
    return self._decode_message(candidate, data, verify, False)
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/conversion.py", line 1349, in _decode_message
    decode_functions.authentication(placeholder)
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/conversion.py", line 1170, in _decode_member_authentication
    members = [member for member in self._community.dispersy.get_members_from_id(member_id) if member.has_identity(self._community)]
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/dispersy.py", line 705, in get_members_from_id
    if public_key]
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/member.py", line 370, in __init__
    super(Member, self).__init__(public_key, private_key)
  File "/home/jenkins/workspace/Test_tribler_full-ui-run_61x/tribler/Tribler/dispersy/member.py", line 154, in __init__
    assert DispersyDatabase.has_instance(), "DispersyDatabase has not yet been created"
AssertionError: DispersyDatabase has not yet been created
E         dispersy/callback:679  _loop                     
```

Can we implement a fix for this? Maybe not process new messages while in the "stopping" state?

**Comment by boudewijn-tribler** [comment]
As far as I know this is related to running the testcases only.  Increasing the timeout (default is now 2 seconds) should solve the problem.

``` python
def stop(self, timeout=2.0):                      
    """                                           
    Stop the callback thread and clean all caches.
    """                                           
    self._callback.stop(timeout=timeout)          
    cleanup_members()                             
    cleanup_singletons()                          
```

As a side note, why was this placed in Dispersy?  This hack is for the testcases only and should not be used in normal operation.  Having it in Dispersy makes it far to accessible to my taste.  Let the testcase 'tear down' mechanism call callback.stop, cleanup_{members, singletons} instead.

**Comment by NielsZeilemaker** [comment]
Both me and Elric agree that this is basic functionality, and should be implemented in any piece of software.
If you can start Dispersy, you should also be able to stop it.

**Comment by NielsZeilemaker** [comment]
The Dispersy.stop method is also called when closing Tribler btw, thus this is causing problem in Tribler as well.

**Comment by boudewijn-tribler** [comment]
Calling `cleanup_singletons()` will cause singletons to be removed.  Anything that requires those singletons will then fail (as Niels points out).  See isse: https://github.com/Tribler/tribler/issues/45.  In Tribler there is no reason to clean the singletons, it should not happen.  Removing the cleanup should fix the problem.

For clarity: `cleanup_singletons` and `cleanup_members`  are hacks that should not be used when running Tribler.
